from __future__ import annotations

import shutil
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "manuscript" / "tables"

SOURCE_TABLES = {
    "day12_external_alignment_sweep.csv": ROOT / "results" / "tables" / "day12_external_alignment_sweep.csv",
    "day13_external_offset_calibration.csv": ROOT / "results" / "tables" / "day13_external_offset_calibration.csv",
    "day13_external_offset_calibration_loo.csv": ROOT / "results" / "tables" / "day13_external_offset_calibration_loo.csv",
}


def require(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Missing required artifact: {path}")


def rmse(s: pd.Series) -> float:
    v = s.astype(float)
    return float((v.pow(2).mean()) ** 0.5)


def mae(s: pd.Series) -> float:
    v = s.astype(float)
    return float(v.abs().mean())


def max_abs(s: pd.Series) -> float:
    v = s.astype(float)
    return float(v.abs().max())


def main() -> None:
    print("Generating manuscript artifacts...")
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for name, src in SOURCE_TABLES.items():
        require(src)
        dst = OUT_DIR / name
        shutil.copyfile(src, dst)
        print(f"Copied {src.relative_to(ROOT)} -> {dst.relative_to(ROOT)}")

    day13 = pd.read_csv(SOURCE_TABLES["day13_external_offset_calibration.csv"])
    loo = pd.read_csv(SOURCE_TABLES["day13_external_offset_calibration_loo.csv"])

    if "calibrated_error_db" not in day13.columns:
        raise RuntimeError("Missing calibrated_error_db column.")
    if "loo_error_db" not in loo.columns:
        raise RuntimeError("Missing loo_error_db column.")

    summary = pd.DataFrame(
        [
            {
                "Validation item": "Day-13 offset-calibrated diagnostic",
                "RMSE (dB)": f"{rmse(day13['calibrated_error_db']):.6f}",
                "MAE (dB)": f"{mae(day13['calibrated_error_db']):.6f}",
                "Max abs. error (dB)": f"{max_abs(day13['calibrated_error_db']):.6f}",
                "Interpretation": "Sub-dB calibrated diagnostic agreement",
            },
            {
                "Validation item": "Day-13 leave-one-out diagnostic",
                "RMSE (dB)": f"{rmse(loo['loo_error_db']):.6f}",
                "MAE (dB)": f"{mae(loo['loo_error_db']):.6f}",
                "Max abs. error (dB)": f"{max_abs(loo['loo_error_db']):.6f}",
                "Interpretation": "Sub-dB LOO calibrated diagnostic agreement",
            },
        ]
    )

    md_path = OUT_DIR / "validation_summary_table.md"
    tex_path = OUT_DIR / "validation_summary_table.tex"
    manifest_path = OUT_DIR / "MANIFEST.md"

    summary.to_markdown(md_path, index=False)

    latex = summary.to_latex(
        index=False,
        escape=True,
        caption=(
            "Summary of calibrated external diagnostic validation. "
            "These results support calibrated trend agreement, not raw absolute GNPy validation."
        ),
        label="tab:validation-summary",
    )
    tex_path.write_text(latex, encoding="utf-8")

    manifest_lines = [
        "# Manuscript Table Manifest",
        "",
        "Generated by:",
        "",
        "`python scripts\\\\generate_manuscript_artifacts.py`",
        "",
        "Generated artifacts:",
        "",
        "- day12_external_alignment_sweep.csv",
        "- day13_external_offset_calibration.csv",
        "- day13_external_offset_calibration_loo.csv",
        "- validation_summary_table.md",
        "- validation_summary_table.tex",
        "",
        "Claim policy:",
        "",
        "These tables support calibrated diagnostic agreement only. They must not be used to claim raw absolute GNPy validation or experimental validation.",
        "",
    ]
    manifest_path.write_text("\n".join(manifest_lines), encoding="utf-8")

    print(f"Wrote {md_path.relative_to(ROOT)}")
    print(f"Wrote {tex_path.relative_to(ROOT)}")
    print(f"Wrote {manifest_path.relative_to(ROOT)}")
    print("Manuscript artifact generation completed.")


if __name__ == "__main__":
    main()
